# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kv_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'kv_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10kv_service.proto\x12\x06shard\"\x19\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"+\n\x0bGetResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\r\n\x05value\x18\x02 \x01(\x0c\"(\n\nPutRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\"-\n\x0bPutResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"\x1c\n\rDeleteRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"!\n\x0e\x44\x65leteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"@\n\x0bScanRequest\x12\x11\n\tstart_key\x18\x01 \x01(\t\x12\x0f\n\x07\x65nd_key\x18\x02 \x01(\t\x12\r\n\x05limit\x18\x03 \x01(\r\"&\n\x08KeyValue\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\"j\n\x07WriteOp\x12$\n\x04type\x18\x01 \x01(\x0e\x32\x16.shard.WriteOp.OpType\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x0c\"\x1d\n\x06OpType\x12\x07\n\x03PUT\x10\x00\x12\n\n\x06\x44\x45LETE\x10\x01\";\n\rBatchResponse\x12\x15\n\rsuccess_count\x18\x01 \x01(\r\x12\x13\n\x0b\x65rror_count\x18\x02 \x01(\r2\x8d\x02\n\tKVService\x12.\n\x03Get\x12\x12.shard.GetRequest\x1a\x13.shard.GetResponse\x12.\n\x03Put\x12\x12.shard.PutRequest\x1a\x13.shard.PutResponse\x12\x37\n\x06\x44\x65lete\x12\x15.shard.DeleteRequest\x1a\x16.shard.DeleteResponse\x12/\n\x04Scan\x12\x13.shard.ScanRequest\x1a\x10.shard.KeyValue0\x01\x12\x36\n\nBatchWrite\x12\x0f.shard.WriteOp\x1a\x15.shard.BatchResponse(\x01\x42\x03\xf8\x01\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kv_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\370\001\001'
  _globals['_GETREQUEST']._serialized_start=28
  _globals['_GETREQUEST']._serialized_end=53
  _globals['_GETRESPONSE']._serialized_start=55
  _globals['_GETRESPONSE']._serialized_end=98
  _globals['_PUTREQUEST']._serialized_start=100
  _globals['_PUTREQUEST']._serialized_end=140
  _globals['_PUTRESPONSE']._serialized_start=142
  _globals['_PUTRESPONSE']._serialized_end=187
  _globals['_DELETEREQUEST']._serialized_start=189
  _globals['_DELETEREQUEST']._serialized_end=217
  _globals['_DELETERESPONSE']._serialized_start=219
  _globals['_DELETERESPONSE']._serialized_end=252
  _globals['_SCANREQUEST']._serialized_start=254
  _globals['_SCANREQUEST']._serialized_end=318
  _globals['_KEYVALUE']._serialized_start=320
  _globals['_KEYVALUE']._serialized_end=358
  _globals['_WRITEOP']._serialized_start=360
  _globals['_WRITEOP']._serialized_end=466
  _globals['_WRITEOP_OPTYPE']._serialized_start=437
  _globals['_WRITEOP_OPTYPE']._serialized_end=466
  _globals['_BATCHRESPONSE']._serialized_start=468
  _globals['_BATCHRESPONSE']._serialized_end=527
  _globals['_KVSERVICE']._serialized_start=530
  _globals['_KVSERVICE']._serialized_end=799
# @@protoc_insertion_point(module_scope)
