# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import kv_service_pb2 as kv__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kv_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KVServiceStub(object):
    """Client-facing key-value operations
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Get = channel.unary_unary(
                '/shard.KVService/Get',
                request_serializer=kv__service__pb2.GetRequest.SerializeToString,
                response_deserializer=kv__service__pb2.GetResponse.FromString,
                _registered_method=True)
        self.Put = channel.unary_unary(
                '/shard.KVService/Put',
                request_serializer=kv__service__pb2.PutRequest.SerializeToString,
                response_deserializer=kv__service__pb2.PutResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/shard.KVService/Delete',
                request_serializer=kv__service__pb2.DeleteRequest.SerializeToString,
                response_deserializer=kv__service__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.Scan = channel.unary_stream(
                '/shard.KVService/Scan',
                request_serializer=kv__service__pb2.ScanRequest.SerializeToString,
                response_deserializer=kv__service__pb2.KeyValue.FromString,
                _registered_method=True)
        self.BatchWrite = channel.stream_unary(
                '/shard.KVService/BatchWrite',
                request_serializer=kv__service__pb2.WriteOp.SerializeToString,
                response_deserializer=kv__service__pb2.BatchResponse.FromString,
                _registered_method=True)


class KVServiceServicer(object):
    """Client-facing key-value operations
    """

    def Get(self, request, context):
        """Retrieve a value by key
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Put(self, request, context):
        """Store a key-value pair
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Remove a key
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Scan(self, request, context):
        """Range scan with server-side streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchWrite(self, request_iterator, context):
        """Batch write for bulk operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KVServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=kv__service__pb2.GetRequest.FromString,
                    response_serializer=kv__service__pb2.GetResponse.SerializeToString,
            ),
            'Put': grpc.unary_unary_rpc_method_handler(
                    servicer.Put,
                    request_deserializer=kv__service__pb2.PutRequest.FromString,
                    response_serializer=kv__service__pb2.PutResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=kv__service__pb2.DeleteRequest.FromString,
                    response_serializer=kv__service__pb2.DeleteResponse.SerializeToString,
            ),
            'Scan': grpc.unary_stream_rpc_method_handler(
                    servicer.Scan,
                    request_deserializer=kv__service__pb2.ScanRequest.FromString,
                    response_serializer=kv__service__pb2.KeyValue.SerializeToString,
            ),
            'BatchWrite': grpc.stream_unary_rpc_method_handler(
                    servicer.BatchWrite,
                    request_deserializer=kv__service__pb2.WriteOp.FromString,
                    response_serializer=kv__service__pb2.BatchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shard.KVService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('shard.KVService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KVService(object):
    """Client-facing key-value operations
    """

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shard.KVService/Get',
            kv__service__pb2.GetRequest.SerializeToString,
            kv__service__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shard.KVService/Put',
            kv__service__pb2.PutRequest.SerializeToString,
            kv__service__pb2.PutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shard.KVService/Delete',
            kv__service__pb2.DeleteRequest.SerializeToString,
            kv__service__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Scan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/shard.KVService/Scan',
            kv__service__pb2.ScanRequest.SerializeToString,
            kv__service__pb2.KeyValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchWrite(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/shard.KVService/BatchWrite',
            kv__service__pb2.WriteOp.SerializeToString,
            kv__service__pb2.BatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
