# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raft_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'raft_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12raft_service.proto\x12\x0bshard.raft\"`\n\x0bVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\x14\n\x0c\x63\x61ndidate_id\x18\x02 \x01(\r\x12\x16\n\x0elast_log_index\x18\x03 \x01(\x04\x12\x15\n\rlast_log_term\x18\x04 \x01(\x04\"2\n\x0cVoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\x14\n\x0cvote_granted\x18\x02 \x01(\x08\"\x9e\x01\n\rAppendRequest\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\x11\n\tleader_id\x18\x02 \x01(\r\x12\x16\n\x0eprev_log_index\x18\x03 \x01(\x04\x12\x15\n\rprev_log_term\x18\x04 \x01(\x04\x12&\n\x07\x65ntries\x18\x05 \x03(\x0b\x32\x15.shard.raft.LogEntry\x12\x15\n\rleader_commit\x18\x06 \x01(\x04\"D\n\x0e\x41ppendResponse\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x13\n\x0bmatch_index\x18\x03 \x01(\x04\"8\n\x08LogEntry\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\r\n\x05index\x18\x02 \x01(\x04\x12\x0f\n\x07\x63ommand\x18\x03 \x01(\x0c\"\x95\x01\n\rSnapshotChunk\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\x11\n\tleader_id\x18\x02 \x01(\r\x12\x1b\n\x13last_included_index\x18\x03 \x01(\x04\x12\x1a\n\x12last_included_term\x18\x04 \x01(\x04\x12\x0e\n\x06offset\x18\x05 \x01(\x04\x12\x0c\n\x04\x64\x61ta\x18\x06 \x01(\x0c\x12\x0c\n\x04\x64one\x18\x07 \x01(\x08\"1\n\x10SnapshotResponse\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\x0f\n\x07success\x18\x02 \x01(\x08\x32\xef\x01\n\x0bRaftService\x12\x42\n\x0bRequestVote\x12\x18.shard.raft.VoteRequest\x1a\x19.shard.raft.VoteResponse\x12L\n\rAppendEntries\x12\x1a.shard.raft.AppendRequest\x1a\x1b.shard.raft.AppendResponse(\x01\x30\x01\x12N\n\x0fInstallSnapshot\x12\x1a.shard.raft.SnapshotChunk\x1a\x1d.shard.raft.SnapshotResponse(\x01\x42\x03\xf8\x01\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\370\001\001'
  _globals['_VOTEREQUEST']._serialized_start=35
  _globals['_VOTEREQUEST']._serialized_end=131
  _globals['_VOTERESPONSE']._serialized_start=133
  _globals['_VOTERESPONSE']._serialized_end=183
  _globals['_APPENDREQUEST']._serialized_start=186
  _globals['_APPENDREQUEST']._serialized_end=344
  _globals['_APPENDRESPONSE']._serialized_start=346
  _globals['_APPENDRESPONSE']._serialized_end=414
  _globals['_LOGENTRY']._serialized_start=416
  _globals['_LOGENTRY']._serialized_end=472
  _globals['_SNAPSHOTCHUNK']._serialized_start=475
  _globals['_SNAPSHOTCHUNK']._serialized_end=624
  _globals['_SNAPSHOTRESPONSE']._serialized_start=626
  _globals['_SNAPSHOTRESPONSE']._serialized_end=675
  _globals['_RAFTSERVICE']._serialized_start=678
  _globals['_RAFTSERVICE']._serialized_end=917
# @@protoc_insertion_point(module_scope)
