# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import raft_service_pb2 as raft__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in raft_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RaftServiceStub(object):
    """Inter-node Raft consensus RPCs
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestVote = channel.unary_unary(
                '/shard.raft.RaftService/RequestVote',
                request_serializer=raft__service__pb2.VoteRequest.SerializeToString,
                response_deserializer=raft__service__pb2.VoteResponse.FromString,
                _registered_method=True)
        self.AppendEntries = channel.stream_stream(
                '/shard.raft.RaftService/AppendEntries',
                request_serializer=raft__service__pb2.AppendRequest.SerializeToString,
                response_deserializer=raft__service__pb2.AppendResponse.FromString,
                _registered_method=True)
        self.InstallSnapshot = channel.stream_unary(
                '/shard.raft.RaftService/InstallSnapshot',
                request_serializer=raft__service__pb2.SnapshotChunk.SerializeToString,
                response_deserializer=raft__service__pb2.SnapshotResponse.FromString,
                _registered_method=True)


class RaftServiceServicer(object):
    """Inter-node Raft consensus RPCs
    """

    def RequestVote(self, request, context):
        """Leader election voting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendEntries(self, request_iterator, context):
        """Log replication with bi-directional streaming for efficiency
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InstallSnapshot(self, request_iterator, context):
        """Snapshot transfer for log compaction
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RaftServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestVote': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestVote,
                    request_deserializer=raft__service__pb2.VoteRequest.FromString,
                    response_serializer=raft__service__pb2.VoteResponse.SerializeToString,
            ),
            'AppendEntries': grpc.stream_stream_rpc_method_handler(
                    servicer.AppendEntries,
                    request_deserializer=raft__service__pb2.AppendRequest.FromString,
                    response_serializer=raft__service__pb2.AppendResponse.SerializeToString,
            ),
            'InstallSnapshot': grpc.stream_unary_rpc_method_handler(
                    servicer.InstallSnapshot,
                    request_deserializer=raft__service__pb2.SnapshotChunk.FromString,
                    response_serializer=raft__service__pb2.SnapshotResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shard.raft.RaftService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('shard.raft.RaftService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RaftService(object):
    """Inter-node Raft consensus RPCs
    """

    @staticmethod
    def RequestVote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shard.raft.RaftService/RequestVote',
            raft__service__pb2.VoteRequest.SerializeToString,
            raft__service__pb2.VoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppendEntries(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/shard.raft.RaftService/AppendEntries',
            raft__service__pb2.AppendRequest.SerializeToString,
            raft__service__pb2.AppendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InstallSnapshot(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/shard.raft.RaftService/InstallSnapshot',
            raft__service__pb2.SnapshotChunk.SerializeToString,
            raft__service__pb2.SnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
